---
galaxy_info:
  author: Jonathan Hanson
  description: A set of configurations for a Raspberry Pi Raspbian device
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  galaxy_tags:
    - raspberrypi
