---
# After a flury of time services, it looks like things settled on timedatectl
# in systemd for the client, and chrony for running a service.
- name: Ensure the alternative time management packages are absent
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items:
    - ntp
    - openntpd

# See: https://documentation.ubuntu.com/server/how-to/networking/timedatectl-and-timesyncd/
- name: Only use a time server client
  when: not secure_device_install_time_server
  block:
    - name: Ensure the Chrony package is absent
      ansible.builtin.package:
        name: chrony
        state: absent

    - name: Determine whether timedatectl is currently enabled
      ansible.builtin.shell: 'set -o pipefail && timedatectl status | grep -oP "(NTP service|systemd-timesyncd.service active): \K\w+"'
      args:
        executable: /bin/bash
      changed_when: false
      register: _timedatectl_enabled
      failed_when: _timedatectl_enabled.rc|int not in (0, 1)

    - name: Ensure timesyncd is enabled
      ansible.builtin.command: "timedatectl set-ntp yes"
      when: _timedatectl_enabled.rc == 0 and _timedatectl_enabled.stdout != "yes" and _timedatectl_enabled.stdout != "active"
      changed_when: true

# See: https://documentation.ubuntu.com/server/how-to/networking/serve-ntp-with-chrony/#serve-ntp-with-chrony
- name: Install a time sync service
  when: secure_device_install_time_server
  block:
    - name: Ensure the Chrony package is present
      ansible.builtin.package:
        name: chrony
        state: present

    - name: Ensure the Chrony configuration file is installed
      ansible.builtin.template:
        src: chrony.conf.j2
        dest: /etc/chrony/chrony.conf
        mode: 0644
      notify: Restart chrony
