---
galaxy_info:
  author: Jonathan Hanson
  description: A basic physical machine preparation role.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags:
    - baremetal
