---
galaxy_info:
  author: Jonathan Hanson
  description: A role responsible for some basic security tweaks for internet-facing machines
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
  galaxy_tags:
    - security
    - usermanagement
