---
- name: Reload ssh
  ansible.builtin.service:
    name: ssh
    state: reloaded

- name: Restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: Reload fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: reloaded
